Save a copy in Drive of the given notebook and make changes.

Output for each of the questions is provided below each question. You need to produce the same output.

In [ ]:
import numpy as np

 1. Create a 4x6 matrix filled with all zeros.

In [ ]:
a = np.zeros((4, 6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


2. Create a 5x5 matrix filled with all ones.

In [ ]:
a = np.ones((5, 5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3.Create a matrix of (4,5) filled with 4.

In [ ]:
a = np.full((4, 5), 4)
print(a)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


For questions 4-13, consider the matrix

a=[[1,2,3],[1,4,5],[8,4,2]]


4. Write a code to get print the shape of the given matrix.




In [ ]:
a = np.matrix([[1,2,3],[1,4,5],[8,4,2]])
print(a.shape)

(3, 3)


5.Write the code to print number of elements in a.

In [ ]:
num_elements = a.size
print("Number of elements in 'a':", num_elements)

Number of elements in 'a': 9


6. Print the 2nd row,1st column and element at (1,2) of a.

In [ ]:
# Entire 2nd row
second_row = a[1, :]
print(second_row)

# Entire 2nd column
second_column = a[:, 1]
print(second_column)

# Printing the element at (1, 2) position (Python indexing starts from 0)
element_1_2_position = a[1, 2]
print(element_1_2_position)

[[1 4 5]]
[[2]
 [4]
 [4]]
5


7. Change the element at (2,1) to 5.

In [ ]:
# Changing the element at (2, 1) to 5
a[2, 1] = 5

print("Matrix a after changing the element at (2, 1) to 5:")
print(a)

Matrix a after changing the element at (2, 1) to 5:
[[1 2 3]
 [1 4 5]
 [8 5 2]]


8. Print the first and the last element of the first row using stepsize approach.

In [ ]:
print("First element of the first row:", a[0, 0])
print("Last element of the first row:", a[0, -1])

First element of the first row: 1
Last element of the first row: 3


9. Print the maximum and minimum values of a.

In [ ]:
# Maximum value in matrix a
max_value = np.max(a)
print("Maximum value in matrix a:", max_value)

# Minimum value in matrix a
min_value = np.min(a)
print("Minimum value in matrix a:", min_value)

Maximum value in matrix a: 8
Minimum value in matrix a: 1


10. Print row-wise maximum values and their indicies of a.

In [ ]:
# Row-wise maximum values
max_values = np.max(a, axis=1)
print(max_values)

# Indices of row-wise maximum values
max_indices = np.argmax(a, axis=1)
print(max_indices)

[[3]
 [5]
 [8]]
[[2]
 [2]
 [0]]


11. Divide all the elements of a by 4.

In [ ]:
print(a/4)

[[0.25 0.5  0.75]
 [0.25 1.   1.25]
 [2.   1.25 0.5 ]]


12. Sort a along the second axis.

In [ ]:
# Sort along the second axis (axis=1), with the first axis being axis = 0
sorted_a = np.sort(a, axis=1)

print(sorted_a)

[[1 2 3]
 [1 4 5]
 [2 5 8]]


13. Print the indices that would sort a along the second axis.

In [ ]:
# Indices that would sort 'a' along the second axis (axis=1)
sorted_indices = np.argsort(a, axis=1)

print(sorted_indices)

[[0 1 2]
 [0 1 2]
 [2 1 0]]


14. Create an identity matrix of size 6x6.

In [ ]:
# Creating a 6x6 identity matrix using np.identity()
identity_matrix = np.identity(6)

print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


15. Let b=[1,4,3,2,6,8,5,4,2,0], split b into 3 arrays each of 3,4,3 elements.

In [ ]:
b = np.array([1, 4, 3, 2, 6, 8, 5, 4, 2, 0])

# Splitting 'b' into arrays of 3, 4, and 3 elements
split_arrays = np.split(b, [3, 7])
# Split b at indices at 3 and 7 to get arrays of 3, 4, and 3 elements

print("Split arrays:")
for arr in split_arrays:
    print(arr)

Split arrays:
[1 4 3]
[2 6 8 5]
[4 2 0]


16.Create a 1-D array of 40 evenly spaced elements between 0. and 1., inclusive.

In [ ]:
# Create a 1-D array of 40 evenly spaced elements between 0 and 1
evenly_spaced_array = np.linspace(0, 1, 40)

print(evenly_spaced_array)

[0.         0.02564103 0.05128205 0.07692308 0.1025641  0.12820513
 0.15384615 0.17948718 0.20512821 0.23076923 0.25641026 0.28205128
 0.30769231 0.33333333 0.35897436 0.38461538 0.41025641 0.43589744
 0.46153846 0.48717949 0.51282051 0.53846154 0.56410256 0.58974359
 0.61538462 0.64102564 0.66666667 0.69230769 0.71794872 0.74358974
 0.76923077 0.79487179 0.82051282 0.84615385 0.87179487 0.8974359
 0.92307692 0.94871795 0.97435897 1.        ]


17. Mutliply given arrays element-wise.

a=[[4,7,2],[1,3,9]]

b=[[1,5,0],[2,7,5]]

In [ ]:
a = np.array([[4, 7, 2], [1, 3, 9]])
b = np.array([[1, 5, 0], [2, 7, 5]])

# Element-wise multiplication of arrays a and b
result = a * b

print(result)

[[ 4 35  0]
 [ 2 21 45]]


18. Create a 3x2 array with random values from 0 to 1.

In [ ]:
# Create a 3x2 array with random values between 0 and 1
random_array = np.random.rand(3, 2)

print(random_array)

[[0.91571935 0.46161929]
 [0.3029408  0.20728249]
 [0.91013246 0.73916609]]
